version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: backtodolist-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: Root
      MONGO_INITDB_ROOT_PASSWORD: Root
    volumes:
      - ./mongo:/data/db

volumes:
  mongodb_data: